import { describe, it, expect } from "vitest";
import { casePortalTargets, resolvePortalTargets } from "./casePortals";
import type { Portal, Task } from "@/types";

function portal(over: Partial<Portal>): Portal {
  return {
    id: "p",
    orgId: "org-1",
    portalKey: "bcbs_ks_enrollment",
    name: "BCBS KS Enrollment",
    payerId: null,
    formUrl: "https://portal.example/bcbs",
    isVerified: true,
    lastVerifiedAt: null,
    urlChangedAt: null,
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-01-01T00:00:00Z",
    ...over,
  };
}

function task(over: Partial<Task>): Task {
  return {
    id: "t",
    orgId: "org-1",
    caseId: "c1",
    providerId: "prov-1",
    title: "Enroll",
    description: null,
    sopContent: [],
    status: "in_progress",
    sortOrder: 1,
    dueDate: null,
    completedDate: null,
    isAutoGenerated: true,
    sopTemplateId: null,
    sopVersion: null,
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-01-01T00:00:00Z",
    ...over,
  };
}

const step = (portalKey?: string) => ({
  id: "s",
  order: 1,
  label: "Fill",
  isCompleted: false,
  portalKey,
});

describe("resolvePortalTargets", () => {
  it("resolves distinct keys to registry name + url, sorted by name", () => {
    const portals = [
      portal({ portalKey: "b_portal", name: "Bravo", formUrl: "https://b" }),
      portal({ portalKey: "a_portal", name: "Alpha", formUrl: "https://a" }),
    ];
    const targets = resolvePortalTargets(["b_portal", "a_portal"], portals);
    expect(targets.map((t) => t.name)).toEqual(["Alpha", "Bravo"]);
    expect(targets[0]).toEqual({ portalKey: "a_portal", name: "Alpha", url: "https://a" });
  });

  it("dedupes normalized keys and skips portals without a formUrl or no registry match", () => {
    const portals = [
      portal({ portalKey: "bcbs_ks_enrollment", name: "BCBS", formUrl: "https://x" }),
      portal({ portalKey: "no_url", name: "No URL", formUrl: null }),
    ];
    const targets = resolvePortalTargets(
      ["BCBS_KS_Enrollment", "bcbs_ks_enrollment", "no_url", "unknown_key"],
      portals,
    );
    expect(targets).toEqual([{ portalKey: "bcbs_ks_enrollment", name: "BCBS", url: "https://x" }]);
  });
});

describe("casePortalTargets", () => {
  it("collects portal keys from non-completed tasks' steps", () => {
    const portals = [
      portal({ portalKey: "bcbs_ks_enrollment", name: "BCBS", formUrl: "https://x" }),
    ];
    const tasks = [
      task({ id: "t1", status: "in_progress", sopContent: [step("bcbs_ks_enrollment")] }),
      task({ id: "t2", status: "completed", sopContent: [step("other_portal")] }),
    ];
    const targets = casePortalTargets(tasks, portals);
    expect(targets).toEqual([{ portalKey: "bcbs_ks_enrollment", name: "BCBS", url: "https://x" }]);
  });

  it("returns nothing when no open task has a resolvable portal", () => {
    expect(casePortalTargets([task({ sopContent: [step(undefined)] })], [])).toEqual([]);
  });
});
