import { describe, expect, it } from "vitest";
import {
  currentStepPointer,
  facilityAddressLine,
  orderedSteps,
  summarizeTasks,
} from "./caseDetailView";
import type { SOPStep, Task } from "@/types";

const step = (over: Partial<SOPStep> & { id: string }): SOPStep => ({
  order: 1,
  label: "Step",
  isCompleted: false,
  ...over,
});

const task = (over: Partial<Task> & { id: string }): Task => ({
  orgId: "org",
  caseId: "case",
  providerId: "pr",
  title: "Task",
  description: null,
  sopContent: [],
  status: "not_started",
  sortOrder: 0,
  dueDate: null,
  completedDate: null,
  isAutoGenerated: true,
  sopTemplateId: null,
  sopVersion: null,
  createdAt: "2026-07-01T00:00:00Z",
  updatedAt: "2026-07-01T00:00:00Z",
  ...over,
});

describe("summarizeTasks", () => {
  it("counts completed of total and names the soonest OPEN due date", () => {
    const out = summarizeTasks([
      task({ id: "t1", status: "completed", dueDate: "2026-08-01" }),
      task({ id: "t2", dueDate: "2026-09-01" }),
      task({ id: "t3", dueDate: "2026-08-15" }),
    ]);
    expect(out).toEqual({ completed: 1, total: 3, nextDueDate: "2026-08-15" });
  });

  it("has no next due date when every open task is dateless", () => {
    expect(summarizeTasks([task({ id: "t1" })]).nextDueDate).toBeNull();
    expect(summarizeTasks([]).nextDueDate).toBeNull();
  });

  it("ignores a completed task's due date", () => {
    const out = summarizeTasks([task({ id: "t1", status: "completed", dueDate: "2026-01-01" })]);
    expect(out).toEqual({ completed: 1, total: 1, nextDueDate: null });
  });
});

describe("currentStepPointer", () => {
  it("points at the first incomplete step of the first unfinished task", () => {
    const out = currentStepPointer([
      task({
        id: "t1",
        status: "completed",
        sopContent: [step({ id: "s0", isCompleted: true })],
      }),
      task({
        id: "t2",
        sopContent: [step({ id: "s1", isCompleted: true }), step({ id: "s2", order: 2 })],
      }),
      task({ id: "t3", sopContent: [step({ id: "s3" })] }),
    ]);
    expect(out).toEqual({ taskId: "t2", stepId: "s2" });
  });

  it("skips an unfinished task whose steps are all done", () => {
    const out = currentStepPointer([
      task({ id: "t1", sopContent: [step({ id: "s1", isCompleted: true })] }),
      task({ id: "t2", sopContent: [step({ id: "s2" })] }),
    ]);
    expect(out).toEqual({ taskId: "t2", stepId: "s2" });
  });

  it("is null when nothing is open (or no task carries steps)", () => {
    expect(currentStepPointer([])).toBeNull();
    expect(currentStepPointer([task({ id: "t1", status: "completed" })])).toBeNull();
    expect(currentStepPointer([task({ id: "t1", sopContent: [] })])).toBeNull();
  });
});

describe("orderedSteps", () => {
  it("sorts by the stored order and keeps array order on ties", () => {
    const out = orderedSteps(
      task({
        id: "t1",
        sopContent: [
          step({ id: "b", order: 2 }),
          step({ id: "a", order: 1 }),
          step({ id: "c", order: 2 }),
        ],
      }),
    );
    expect(out.map((s) => s.id)).toEqual(["a", "b", "c"]);
  });

  it("tolerates a task with no steps", () => {
    expect(orderedSteps(task({ id: "t1" }))).toEqual([]);
  });
});

describe("facilityAddressLine", () => {
  it("composes street/suite · city, state zip", () => {
    expect(
      facilityAddressLine({
        street: "12 Figure Eight Rd",
        suite: "Suite 200",
        city: "Boulder",
        state: "CO",
        zip: "80301",
      }),
    ).toBe("12 Figure Eight Rd, Suite 200 · Boulder, CO 80301");
  });

  it("drops absent parts instead of leaving punctuation", () => {
    expect(facilityAddressLine({ street: "12 Main St", city: null, state: "CO", zip: null })).toBe(
      "12 Main St · CO",
    );
    expect(facilityAddressLine({ city: "Boulder", state: "CO", zip: "80301" })).toBe(
      "Boulder, CO 80301",
    );
  });

  it("is null for no facility and for an address-less facility", () => {
    expect(facilityAddressLine(null)).toBeNull();
    expect(facilityAddressLine({ street: null, city: null, state: null, zip: null })).toBeNull();
    expect(facilityAddressLine({ street: "  " })).toBeNull();
  });
});
