import { useMemo, useState } from "react";
import { Link } from "@tanstack/react-router";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { useSops } from "@/hooks/useAdmin";
import { useReplaceCaseSop } from "@/hooks/useCases";
import { isAllStates, templateStates } from "@/lib/sopMatchKey";
import { isFallbackTemplate, topRankedTemplates } from "@/lib/pickTemplate";
import { resolveTemplate } from "@/lib/sopResolver";
import type { CaseDetail } from "@/types";

export function ChangeCaseSopAction({ c, canEdit }: { c: CaseDetail; canEdit: boolean }) {
  const templatesQ = useSops();
  const replace = useReplaceCaseSop();
  const [open, setOpen] = useState(false);
  const [selectedId, setSelectedId] = useState("");

  const options = useMemo(
    () =>
      (templatesQ.data ?? []).filter((t) => {
        if (t.archived || !t.currentVersion || (t.caseType ?? null) !== (c.caseType ?? null))
          return false;
        if (isFallbackTemplate(t)) return true;
        if (t.payerId !== c.payerId) return false;
        if (t.groupId !== null && t.groupId !== c.groupId) return false;
        const states = templateStates(t);
        return isAllStates(states) || states.includes(c.state);
      }),
    [templatesQ.data, c.payerId, c.groupId, c.state, c.caseType],
  );
  const tasks = c.tasks ?? [];
  const currentTemplateId = tasks.find((t) => t.sopTemplateId)?.sopTemplateId ?? null;
  const untouched = tasks.every(
    (t) =>
      t.isAutoGenerated &&
      t.status === "not_started" &&
      !t.completedDate &&
      !t.sopContent?.some((step) => step.isCompleted || (step.attachments?.length ?? 0) > 0),
  );
  const available =
    canEdit &&
    c.provider != null &&
    (c.caseStatus === "not_started" || c.caseStatus === "in_progress") &&
    untouched &&
    c.caseType !== "recredentialing";
  if (
    c.caseType === "recredentialing" &&
    canEdit &&
    (c.caseStatus === "not_started" || c.caseStatus === "in_progress")
  ) {
    return (
      <p className="rounded-md border border-amber-200 bg-amber-50 p-3 text-[13px] text-amber-900">
        Recredentialing execution is not supported. This SOP type is available for authoring only.
      </p>
    );
  }
  if (
    c.caseType === "contract" &&
    canEdit &&
    (c.caseStatus === "not_started" || c.caseStatus === "in_progress")
  ) {
    return (
      <p className="rounded-md border border-amber-200 bg-amber-50 p-3 text-[13px] text-amber-900">
        Contract work belongs in the Group Contracts Matrix and cannot be changed as a provider
        case.
        {c.groupId && c.payerId && c.state ? (
          <Button asChild variant="link" size="sm" className="h-auto px-1 py-0">
            <Link
              to="/reporting/contracts-matrix"
              search={{ groupId: c.groupId, payerId: c.payerId, state: c.state }}
            >
              Open matching Matrix cell
            </Link>
          </Button>
        ) : null}
      </p>
    );
  }
  if (!available) return null;

  const alternatives = options.filter((t) => t.id !== currentTemplateId);

  const chosen = options.find((t) => t.id === selectedId) ?? null;
  const save = () => {
    if (!chosen || !c.provider || !chosen.currentVersion) return;
    const resolved = resolveTemplate(chosen, c.provider, c.group, null, null);
    replace.mutate(
      {
        caseId: c.id,
        templateId: chosen.id,
        expectedVersion: chosen.currentVersion,
        tasks: resolved,
      },
      {
        onSuccess: () => {
          setOpen(false);
          setSelectedId("");
          toast.success(`Case checklist changed to ${chosen.name}.`);
        },
        onError: (error) =>
          toast.error(error instanceof Error ? error.message : "Could not change the template."),
      },
    );
  };

  return (
    <div className="rounded-md border border-border p-3 flex flex-wrap items-center gap-2 text-[13px]">
      <span className="text-muted-foreground">This case’s checklist has not been started.</span>
      {alternatives.length > 0 ? (
        <Button variant="outline" size="sm" className="ml-auto h-8" onClick={() => setOpen(true)}>
          Change template
        </Button>
      ) : (
        <span className="w-full text-[12px] text-amber-800">
          No other {c.caseType ?? "legacy / unclassified"} SOP matches this payer, state, and group.
          <Button asChild variant="link" size="sm" className="h-auto px-1 py-0">
            <Link
              to="/admin/payer-admin/setup/$payerId"
              params={{ payerId: c.payerId }}
              search={{ tab: "templates" }}
            >
              Open payer templates
            </Link>
          </Button>
        </span>
      )}
      {open ? (
        <Dialog open onOpenChange={(next) => !next && setOpen(false)}>
          <DialogContent className="max-w-md">
            <DialogHeader>
              <DialogTitle>Change case template</DialogTitle>
            </DialogHeader>
            <p className="text-[13px] text-muted-foreground">
              Replace the unstarted checklist with tasks from the selected template. The case and
              its history stay in place.
            </p>
            <div className="space-y-1.5">
              <Label htmlFor="case-template-choice">Template to apply</Label>
              <Select value={selectedId} onValueChange={setSelectedId}>
                <SelectTrigger id="case-template-choice">
                  <SelectValue placeholder="Select a template" />
                </SelectTrigger>
                <SelectContent>
                  {alternatives.map((t) => (
                    <SelectItem key={t.id} value={t.id} disabled={t.id === currentTemplateId}>
                      {t.name}
                      {t.taskDefinitions?.length
                        ? ` (${t.taskDefinitions.length} task${t.taskDefinitions.length === 1 ? "" : "s"})`
                        : ""}
                      {t.id === currentTemplateId ? " (current)" : ""}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
              {topRankedTemplates(
                templatesQ.data ?? [],
                c.payerId,
                c.state,
                c.groupId,
                c.caseType ?? null,
              ).length > 1 ? (
                <p className="text-[11px] text-muted-foreground">
                  Several equally ranked {c.caseType ?? "legacy / unclassified"} SOPs match. The
                  list includes all eligible same-type SOPs.
                </p>
              ) : null}
            </div>
            <DialogFooter>
              <Button variant="outline" onClick={() => setOpen(false)}>
                Cancel
              </Button>
              <Button
                disabled={!chosen || chosen.id === currentTemplateId || replace.isPending}
                onClick={save}
              >
                {replace.isPending ? "Changing…" : "Replace checklist"}
              </Button>
            </DialogFooter>
          </DialogContent>
        </Dialog>
      ) : null}
    </div>
  );
}
