import { useMemo, useState } from "react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { useSops } from "@/hooks/useAdmin";
import { useReplaceCaseSop } from "@/hooks/useCases";
import { isAllStates, templateStates } from "@/lib/sopMatchKey";
import { resolveTemplate } from "@/lib/sopResolver";
import type { CaseDetail } from "@/types";

export function ChangeCaseSopAction({ c, canEdit }: { c: CaseDetail; canEdit: boolean }) {
  const templatesQ = useSops();
  const replace = useReplaceCaseSop();
  const [open, setOpen] = useState(false);
  const [selectedId, setSelectedId] = useState("");

  const options = useMemo(
    () =>
      (templatesQ.data ?? []).filter((t) => {
        if (t.archived || !t.currentVersion || t.payerId !== c.payerId) return false;
        if (t.groupId !== null && t.groupId !== c.groupId) return false;
        const states = templateStates(t);
        return isAllStates(states) || states.includes(c.state);
      }),
    [templatesQ.data, c.payerId, c.groupId, c.state],
  );
  const tasks = c.tasks ?? [];
  const currentTemplateId = tasks.find((t) => t.sopTemplateId)?.sopTemplateId ?? null;
  const untouched = tasks.every(
    (t) =>
      t.isAutoGenerated &&
      t.status === "not_started" &&
      !t.completedDate &&
      !t.sopContent?.some((step) => step.isCompleted || (step.attachments?.length ?? 0) > 0),
  );
  const available =
    canEdit &&
    c.provider != null &&
    (c.caseStatus === "not_started" || c.caseStatus === "in_progress") &&
    untouched &&
    options.some((t) => t.id !== currentTemplateId);
  if (!available) return null;

  const chosen = options.find((t) => t.id === selectedId) ?? null;
  const save = () => {
    if (!chosen || !c.provider || !chosen.currentVersion) return;
    const resolved = resolveTemplate(chosen, c.provider, c.group, null, null);
    replace.mutate(
      {
        caseId: c.id,
        templateId: chosen.id,
        expectedVersion: chosen.currentVersion,
        tasks: resolved,
      },
      {
        onSuccess: () => {
          setOpen(false);
          setSelectedId("");
          toast.success(`Case checklist changed to ${chosen.name}.`);
        },
        onError: (error) =>
          toast.error(error instanceof Error ? error.message : "Could not change the template."),
      },
    );
  };

  return (
    <div className="rounded-md border border-border p-3 flex flex-wrap items-center gap-2 text-[13px]">
      <span className="text-muted-foreground">This case’s checklist has not been started.</span>
      <Button variant="outline" size="sm" className="ml-auto h-8" onClick={() => setOpen(true)}>
        Change template
      </Button>
      {open ? (
        <Dialog open onOpenChange={(next) => !next && setOpen(false)}>
          <DialogContent className="max-w-md">
            <DialogHeader>
              <DialogTitle>Change case template</DialogTitle>
            </DialogHeader>
            <p className="text-[13px] text-muted-foreground">
              Replace the unstarted checklist with tasks from the selected template. The case and
              its history stay in place.
            </p>
            <div className="space-y-1.5">
              <Label htmlFor="case-template-choice">Template to apply</Label>
              <Select value={selectedId} onValueChange={setSelectedId}>
                <SelectTrigger id="case-template-choice">
                  <SelectValue placeholder="Select a template" />
                </SelectTrigger>
                <SelectContent>
                  {options.map((t) => (
                    <SelectItem key={t.id} value={t.id} disabled={t.id === currentTemplateId}>
                      {t.name}
                      {t.taskDefinitions?.length
                        ? ` (${t.taskDefinitions.length} task${t.taskDefinitions.length === 1 ? "" : "s"})`
                        : ""}
                      {t.id === currentTemplateId ? " (current)" : ""}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <DialogFooter>
              <Button variant="outline" onClick={() => setOpen(false)}>
                Cancel
              </Button>
              <Button
                disabled={!chosen || chosen.id === currentTemplateId || replace.isPending}
                onClick={save}
              >
                {replace.isPending ? "Changing…" : "Replace checklist"}
              </Button>
            </DialogFooter>
          </DialogContent>
        </Dialog>
      ) : null}
    </div>
  );
}
