import { renderToStaticMarkup } from "react-dom/server";
import { describe, expect, it, vi } from "vitest";
import type { CaseDetail } from "@/types";

const templates = vi.hoisted(() => [
  {
    id: "current",
    name: "Aetna Colorado initial",
    payerId: "aetna",
    states: ["CO"],
    groupId: null,
    archived: false,
    currentVersion: 1,
    taskDefinitions: [{ title: "Email" }],
  },
  {
    id: "alternative",
    name: "Aetna Colorado alternate",
    payerId: "aetna",
    states: ["CO"],
    groupId: null,
    archived: false,
    currentVersion: 2,
    taskDefinitions: [{ title: "Portal" }],
  },
]);

vi.mock("@/hooks/useAdmin", () => ({ useSops: () => ({ data: templates }) }));
vi.mock("@/hooks/useCases", () => ({
  useReplaceCaseSop: () => ({ mutate: vi.fn(), isPending: false }),
}));

import { ChangeCaseSopAction } from "./ChangeCaseSopAction";

const baseCase = {
  id: "case-1",
  payerId: "aetna",
  groupId: "group-1",
  state: "CO",
  caseStatus: "not_started",
  provider: { id: "provider-1" },
  tasks: [
    {
      id: "task-1",
      sopTemplateId: "current",
      isAutoGenerated: true,
      status: "not_started",
      completedDate: null,
      sopContent: [{ isCompleted: false }],
    },
  ],
} as unknown as CaseDetail;

describe("ChangeCaseSopAction", () => {
  it("offers a different matching template on an untouched case", () => {
    const html = renderToStaticMarkup(<ChangeCaseSopAction c={baseCase} canEdit />);
    expect(html).toContain("Change template");
  });

  it("does not offer replacement after task work begins", () => {
    const c = {
      ...baseCase,
      tasks: [{ ...baseCase.tasks[0], status: "in_progress" }],
    } as CaseDetail;
    const html = renderToStaticMarkup(<ChangeCaseSopAction c={c} canEdit />);
    expect(html).not.toContain("Change template");
  });

  it("does not offer replacement to a read-only viewer", () => {
    const html = renderToStaticMarkup(<ChangeCaseSopAction c={baseCase} canEdit={false} />);
    expect(html).not.toContain("Change template");
  });
});
