/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProvidersRouteImport } from './routes/providers'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LaunchesRouteImport } from './routes/launches'
import { Route as HomeRouteImport } from './routes/home'
import { Route as CasesRouteImport } from './routes/cases'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProvidersIndexRouteImport } from './routes/providers.index'
import { Route as LaunchesIndexRouteImport } from './routes/launches.index'
import { Route as CasesIndexRouteImport } from './routes/cases.index'
import { Route as TasksIdRouteImport } from './routes/tasks.$id'
import { Route as ProvidersNewRouteImport } from './routes/providers.new'
import { Route as ProvidersIdRouteImport } from './routes/providers.$id'
import { Route as LaunchesIdRouteImport } from './routes/launches.$id'
import { Route as DevPrimitivesRouteImport } from './routes/dev.primitives'
import { Route as CasesIdRouteImport } from './routes/cases.$id'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTemplatesRouteImport } from './routes/admin.templates'
import { Route as AdminStatusesRouteImport } from './routes/admin.statuses'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminPayersRouteImport } from './routes/admin.payers'
import { Route as AdminMsoRoutingRouteImport } from './routes/admin.mso-routing'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as ProvidersIdIndexRouteImport } from './routes/providers.$id.index'
import { Route as AdminTemplatesIndexRouteImport } from './routes/admin.templates.index'
import { Route as ProvidersIdEditRouteImport } from './routes/providers.$id.edit'
import { Route as AdminTemplatesIdRouteImport } from './routes/admin.templates.$id'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersRoute = ProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchesRoute = LaunchesRouteImport.update({
  id: '/launches',
  path: '/launches',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesRoute = CasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersIndexRoute = ProvidersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProvidersRoute,
} as any)
const LaunchesIndexRoute = LaunchesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LaunchesRoute,
} as any)
const CasesIndexRoute = CasesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CasesRoute,
} as any)
const TasksIdRoute = TasksIdRouteImport.update({
  id: '/tasks/$id',
  path: '/tasks/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersNewRoute = ProvidersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ProvidersRoute,
} as any)
const ProvidersIdRoute = ProvidersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProvidersRoute,
} as any)
const LaunchesIdRoute = LaunchesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LaunchesRoute,
} as any)
const DevPrimitivesRoute = DevPrimitivesRouteImport.update({
  id: '/dev/primitives',
  path: '/dev/primitives',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesIdRoute = CasesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CasesRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTemplatesRoute = AdminTemplatesRouteImport.update({
  id: '/admin/templates',
  path: '/admin/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStatusesRoute = AdminStatusesRouteImport.update({
  id: '/admin/statuses',
  path: '/admin/statuses',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPayersRoute = AdminPayersRouteImport.update({
  id: '/admin/payers',
  path: '/admin/payers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMsoRoutingRoute = AdminMsoRoutingRouteImport.update({
  id: '/admin/mso-routing',
  path: '/admin/mso-routing',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersIdIndexRoute = ProvidersIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProvidersIdRoute,
} as any)
const AdminTemplatesIndexRoute = AdminTemplatesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminTemplatesRoute,
} as any)
const ProvidersIdEditRoute = ProvidersIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ProvidersIdRoute,
} as any)
const AdminTemplatesIdRoute = AdminTemplatesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminTemplatesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cases': typeof CasesRouteWithChildren
  '/home': typeof HomeRoute
  '/launches': typeof LaunchesRouteWithChildren
  '/login': typeof LoginRoute
  '/progress': typeof ProgressRoute
  '/providers': typeof ProvidersRouteWithChildren
  '/reports': typeof ReportsRoute
  '/welcome': typeof WelcomeRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/mso-routing': typeof AdminMsoRoutingRoute
  '/admin/payers': typeof AdminPayersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/statuses': typeof AdminStatusesRoute
  '/admin/templates': typeof AdminTemplatesRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/cases/$id': typeof CasesIdRoute
  '/dev/primitives': typeof DevPrimitivesRoute
  '/launches/$id': typeof LaunchesIdRoute
  '/providers/$id': typeof ProvidersIdRouteWithChildren
  '/providers/new': typeof ProvidersNewRoute
  '/tasks/$id': typeof TasksIdRoute
  '/cases/': typeof CasesIndexRoute
  '/launches/': typeof LaunchesIndexRoute
  '/providers/': typeof ProvidersIndexRoute
  '/admin/templates/$id': typeof AdminTemplatesIdRoute
  '/providers/$id/edit': typeof ProvidersIdEditRoute
  '/admin/templates/': typeof AdminTemplatesIndexRoute
  '/providers/$id/': typeof ProvidersIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/progress': typeof ProgressRoute
  '/reports': typeof ReportsRoute
  '/welcome': typeof WelcomeRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/mso-routing': typeof AdminMsoRoutingRoute
  '/admin/payers': typeof AdminPayersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/statuses': typeof AdminStatusesRoute
  '/admin/users': typeof AdminUsersRoute
  '/cases/$id': typeof CasesIdRoute
  '/dev/primitives': typeof DevPrimitivesRoute
  '/launches/$id': typeof LaunchesIdRoute
  '/providers/new': typeof ProvidersNewRoute
  '/tasks/$id': typeof TasksIdRoute
  '/cases': typeof CasesIndexRoute
  '/launches': typeof LaunchesIndexRoute
  '/providers': typeof ProvidersIndexRoute
  '/admin/templates/$id': typeof AdminTemplatesIdRoute
  '/providers/$id/edit': typeof ProvidersIdEditRoute
  '/admin/templates': typeof AdminTemplatesIndexRoute
  '/providers/$id': typeof ProvidersIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cases': typeof CasesRouteWithChildren
  '/home': typeof HomeRoute
  '/launches': typeof LaunchesRouteWithChildren
  '/login': typeof LoginRoute
  '/progress': typeof ProgressRoute
  '/providers': typeof ProvidersRouteWithChildren
  '/reports': typeof ReportsRoute
  '/welcome': typeof WelcomeRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/mso-routing': typeof AdminMsoRoutingRoute
  '/admin/payers': typeof AdminPayersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/statuses': typeof AdminStatusesRoute
  '/admin/templates': typeof AdminTemplatesRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/cases/$id': typeof CasesIdRoute
  '/dev/primitives': typeof DevPrimitivesRoute
  '/launches/$id': typeof LaunchesIdRoute
  '/providers/$id': typeof ProvidersIdRouteWithChildren
  '/providers/new': typeof ProvidersNewRoute
  '/tasks/$id': typeof TasksIdRoute
  '/cases/': typeof CasesIndexRoute
  '/launches/': typeof LaunchesIndexRoute
  '/providers/': typeof ProvidersIndexRoute
  '/admin/templates/$id': typeof AdminTemplatesIdRoute
  '/providers/$id/edit': typeof ProvidersIdEditRoute
  '/admin/templates/': typeof AdminTemplatesIndexRoute
  '/providers/$id/': typeof ProvidersIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cases'
    | '/home'
    | '/launches'
    | '/login'
    | '/progress'
    | '/providers'
    | '/reports'
    | '/welcome'
    | '/admin/audit'
    | '/admin/mso-routing'
    | '/admin/payers'
    | '/admin/settings'
    | '/admin/statuses'
    | '/admin/templates'
    | '/admin/users'
    | '/cases/$id'
    | '/dev/primitives'
    | '/launches/$id'
    | '/providers/$id'
    | '/providers/new'
    | '/tasks/$id'
    | '/cases/'
    | '/launches/'
    | '/providers/'
    | '/admin/templates/$id'
    | '/providers/$id/edit'
    | '/admin/templates/'
    | '/providers/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/login'
    | '/progress'
    | '/reports'
    | '/welcome'
    | '/admin/audit'
    | '/admin/mso-routing'
    | '/admin/payers'
    | '/admin/settings'
    | '/admin/statuses'
    | '/admin/users'
    | '/cases/$id'
    | '/dev/primitives'
    | '/launches/$id'
    | '/providers/new'
    | '/tasks/$id'
    | '/cases'
    | '/launches'
    | '/providers'
    | '/admin/templates/$id'
    | '/providers/$id/edit'
    | '/admin/templates'
    | '/providers/$id'
  id:
    | '__root__'
    | '/'
    | '/cases'
    | '/home'
    | '/launches'
    | '/login'
    | '/progress'
    | '/providers'
    | '/reports'
    | '/welcome'
    | '/admin/audit'
    | '/admin/mso-routing'
    | '/admin/payers'
    | '/admin/settings'
    | '/admin/statuses'
    | '/admin/templates'
    | '/admin/users'
    | '/cases/$id'
    | '/dev/primitives'
    | '/launches/$id'
    | '/providers/$id'
    | '/providers/new'
    | '/tasks/$id'
    | '/cases/'
    | '/launches/'
    | '/providers/'
    | '/admin/templates/$id'
    | '/providers/$id/edit'
    | '/admin/templates/'
    | '/providers/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CasesRoute: typeof CasesRouteWithChildren
  HomeRoute: typeof HomeRoute
  LaunchesRoute: typeof LaunchesRouteWithChildren
  LoginRoute: typeof LoginRoute
  ProgressRoute: typeof ProgressRoute
  ProvidersRoute: typeof ProvidersRouteWithChildren
  ReportsRoute: typeof ReportsRoute
  WelcomeRoute: typeof WelcomeRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminMsoRoutingRoute: typeof AdminMsoRoutingRoute
  AdminPayersRoute: typeof AdminPayersRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStatusesRoute: typeof AdminStatusesRoute
  AdminTemplatesRoute: typeof AdminTemplatesRouteWithChildren
  AdminUsersRoute: typeof AdminUsersRoute
  DevPrimitivesRoute: typeof DevPrimitivesRoute
  TasksIdRoute: typeof TasksIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers': {
      id: '/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof ProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launches': {
      id: '/launches'
      path: '/launches'
      fullPath: '/launches'
      preLoaderRoute: typeof LaunchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers/': {
      id: '/providers/'
      path: '/'
      fullPath: '/providers/'
      preLoaderRoute: typeof ProvidersIndexRouteImport
      parentRoute: typeof ProvidersRoute
    }
    '/launches/': {
      id: '/launches/'
      path: '/'
      fullPath: '/launches/'
      preLoaderRoute: typeof LaunchesIndexRouteImport
      parentRoute: typeof LaunchesRoute
    }
    '/cases/': {
      id: '/cases/'
      path: '/'
      fullPath: '/cases/'
      preLoaderRoute: typeof CasesIndexRouteImport
      parentRoute: typeof CasesRoute
    }
    '/tasks/$id': {
      id: '/tasks/$id'
      path: '/tasks/$id'
      fullPath: '/tasks/$id'
      preLoaderRoute: typeof TasksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers/new': {
      id: '/providers/new'
      path: '/new'
      fullPath: '/providers/new'
      preLoaderRoute: typeof ProvidersNewRouteImport
      parentRoute: typeof ProvidersRoute
    }
    '/providers/$id': {
      id: '/providers/$id'
      path: '/$id'
      fullPath: '/providers/$id'
      preLoaderRoute: typeof ProvidersIdRouteImport
      parentRoute: typeof ProvidersRoute
    }
    '/launches/$id': {
      id: '/launches/$id'
      path: '/$id'
      fullPath: '/launches/$id'
      preLoaderRoute: typeof LaunchesIdRouteImport
      parentRoute: typeof LaunchesRoute
    }
    '/dev/primitives': {
      id: '/dev/primitives'
      path: '/dev/primitives'
      fullPath: '/dev/primitives'
      preLoaderRoute: typeof DevPrimitivesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/$id': {
      id: '/cases/$id'
      path: '/$id'
      fullPath: '/cases/$id'
      preLoaderRoute: typeof CasesIdRouteImport
      parentRoute: typeof CasesRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/templates': {
      id: '/admin/templates'
      path: '/admin/templates'
      fullPath: '/admin/templates'
      preLoaderRoute: typeof AdminTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/statuses': {
      id: '/admin/statuses'
      path: '/admin/statuses'
      fullPath: '/admin/statuses'
      preLoaderRoute: typeof AdminStatusesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payers': {
      id: '/admin/payers'
      path: '/admin/payers'
      fullPath: '/admin/payers'
      preLoaderRoute: typeof AdminPayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/mso-routing': {
      id: '/admin/mso-routing'
      path: '/admin/mso-routing'
      fullPath: '/admin/mso-routing'
      preLoaderRoute: typeof AdminMsoRoutingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers/$id/': {
      id: '/providers/$id/'
      path: '/'
      fullPath: '/providers/$id/'
      preLoaderRoute: typeof ProvidersIdIndexRouteImport
      parentRoute: typeof ProvidersIdRoute
    }
    '/admin/templates/': {
      id: '/admin/templates/'
      path: '/'
      fullPath: '/admin/templates/'
      preLoaderRoute: typeof AdminTemplatesIndexRouteImport
      parentRoute: typeof AdminTemplatesRoute
    }
    '/providers/$id/edit': {
      id: '/providers/$id/edit'
      path: '/edit'
      fullPath: '/providers/$id/edit'
      preLoaderRoute: typeof ProvidersIdEditRouteImport
      parentRoute: typeof ProvidersIdRoute
    }
    '/admin/templates/$id': {
      id: '/admin/templates/$id'
      path: '/$id'
      fullPath: '/admin/templates/$id'
      preLoaderRoute: typeof AdminTemplatesIdRouteImport
      parentRoute: typeof AdminTemplatesRoute
    }
  }
}

interface CasesRouteChildren {
  CasesIdRoute: typeof CasesIdRoute
  CasesIndexRoute: typeof CasesIndexRoute
}

const CasesRouteChildren: CasesRouteChildren = {
  CasesIdRoute: CasesIdRoute,
  CasesIndexRoute: CasesIndexRoute,
}

const CasesRouteWithChildren = CasesRoute._addFileChildren(CasesRouteChildren)

interface LaunchesRouteChildren {
  LaunchesIdRoute: typeof LaunchesIdRoute
  LaunchesIndexRoute: typeof LaunchesIndexRoute
}

const LaunchesRouteChildren: LaunchesRouteChildren = {
  LaunchesIdRoute: LaunchesIdRoute,
  LaunchesIndexRoute: LaunchesIndexRoute,
}

const LaunchesRouteWithChildren = LaunchesRoute._addFileChildren(
  LaunchesRouteChildren,
)

interface ProvidersIdRouteChildren {
  ProvidersIdEditRoute: typeof ProvidersIdEditRoute
  ProvidersIdIndexRoute: typeof ProvidersIdIndexRoute
}

const ProvidersIdRouteChildren: ProvidersIdRouteChildren = {
  ProvidersIdEditRoute: ProvidersIdEditRoute,
  ProvidersIdIndexRoute: ProvidersIdIndexRoute,
}

const ProvidersIdRouteWithChildren = ProvidersIdRoute._addFileChildren(
  ProvidersIdRouteChildren,
)

interface ProvidersRouteChildren {
  ProvidersIdRoute: typeof ProvidersIdRouteWithChildren
  ProvidersNewRoute: typeof ProvidersNewRoute
  ProvidersIndexRoute: typeof ProvidersIndexRoute
}

const ProvidersRouteChildren: ProvidersRouteChildren = {
  ProvidersIdRoute: ProvidersIdRouteWithChildren,
  ProvidersNewRoute: ProvidersNewRoute,
  ProvidersIndexRoute: ProvidersIndexRoute,
}

const ProvidersRouteWithChildren = ProvidersRoute._addFileChildren(
  ProvidersRouteChildren,
)

interface AdminTemplatesRouteChildren {
  AdminTemplatesIdRoute: typeof AdminTemplatesIdRoute
  AdminTemplatesIndexRoute: typeof AdminTemplatesIndexRoute
}

const AdminTemplatesRouteChildren: AdminTemplatesRouteChildren = {
  AdminTemplatesIdRoute: AdminTemplatesIdRoute,
  AdminTemplatesIndexRoute: AdminTemplatesIndexRoute,
}

const AdminTemplatesRouteWithChildren = AdminTemplatesRoute._addFileChildren(
  AdminTemplatesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CasesRoute: CasesRouteWithChildren,
  HomeRoute: HomeRoute,
  LaunchesRoute: LaunchesRouteWithChildren,
  LoginRoute: LoginRoute,
  ProgressRoute: ProgressRoute,
  ProvidersRoute: ProvidersRouteWithChildren,
  ReportsRoute: ReportsRoute,
  WelcomeRoute: WelcomeRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminMsoRoutingRoute: AdminMsoRoutingRoute,
  AdminPayersRoute: AdminPayersRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStatusesRoute: AdminStatusesRoute,
  AdminTemplatesRoute: AdminTemplatesRouteWithChildren,
  AdminUsersRoute: AdminUsersRoute,
  DevPrimitivesRoute: DevPrimitivesRoute,
  TasksIdRoute: TasksIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
