/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkRouteImport } from './routes/work'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as SoonRouteImport } from './routes/soon'
import { Route as ScopeRouteImport } from './routes/scope'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProvidersRouteImport } from './routes/providers'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PayerDirectoryRouteImport } from './routes/payer-directory'
import { Route as OutcomesRouteImport } from './routes/outcomes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LaunchesRouteImport } from './routes/launches'
import { Route as HomeRouteImport } from './routes/home'
import { Route as GetStartedRouteImport } from './routes/get-started'
import { Route as GenerationRouteImport } from './routes/generation'
import { Route as FixItRouteImport } from './routes/fix-it'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ClientProgressRouteImport } from './routes/client-progress'
import { Route as CasesRouteImport } from './routes/cases'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportingIndexRouteImport } from './routes/reporting.index'
import { Route as ProvidersIndexRouteImport } from './routes/providers.index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding.index'
import { Route as LaunchesIndexRouteImport } from './routes/launches.index'
import { Route as CasesIndexRouteImport } from './routes/cases.index'
import { Route as TasksIdRouteImport } from './routes/tasks.$id'
import { Route as ShareTokenRouteImport } from './routes/share.$token'
import { Route as ReportingPortfolioRouteImport } from './routes/reporting.portfolio'
import { Route as ProvidersNewRouteImport } from './routes/providers.new'
import { Route as ProvidersIdRouteImport } from './routes/providers.$id'
import { Route as OnboardingWizardRouteImport } from './routes/onboarding.wizard'
import { Route as LaunchesIdRouteImport } from './routes/launches.$id'
import { Route as GenerationRunsRouteImport } from './routes/generation_.runs'
import { Route as DevPrimitivesRouteImport } from './routes/dev.primitives'
import { Route as CasesIdRouteImport } from './routes/cases.$id'
import { Route as CaptureTokenRouteImport } from './routes/capture.$token'
import { Route as AdminTemplatesRouteImport } from './routes/admin.templates'
import { Route as AdminStatusesRouteImport } from './routes/admin.statuses'
import { Route as AdminSopsRouteImport } from './routes/admin.sops'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminPortalsRouteImport } from './routes/admin.portals'
import { Route as AdminPayersRouteImport } from './routes/admin.payers'
import { Route as AdminMsoRoutingRouteImport } from './routes/admin.mso-routing'
import { Route as AdminImportRouteImport } from './routes/admin.import'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as ProvidersIdIndexRouteImport } from './routes/providers.$id.index'
import { Route as GenerationRunsIndexRouteImport } from './routes/generation_.runs.index'
import { Route as AdminTemplatesIndexRouteImport } from './routes/admin.templates.index'
import { Route as AdminSopsIndexRouteImport } from './routes/admin.sops.index'
import { Route as ProvidersIdEditRouteImport } from './routes/providers.$id.edit'
import { Route as PortalsPortalKeyTrainRouteImport } from './routes/portals.$portalKey.train'
import { Route as GenerationRunsRunIdRouteImport } from './routes/generation_.runs.$runId'
import { Route as AdminTemplatesNewRouteImport } from './routes/admin.templates.new'
import { Route as AdminTemplatesIdRouteImport } from './routes/admin.templates.$id'
import { Route as AdminSopsIdRouteImport } from './routes/admin.sops.$id'
import { Route as AdminPayersIdScorecardRouteImport } from './routes/admin.payers_.$id.scorecard'

const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const SoonRoute = SoonRouteImport.update({
  id: '/soon',
  path: '/soon',
  getParentRoute: () => rootRouteImport,
} as any)
const ScopeRoute = ScopeRouteImport.update({
  id: '/scope',
  path: '/scope',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersRoute = ProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PayerDirectoryRoute = PayerDirectoryRouteImport.update({
  id: '/payer-directory',
  path: '/payer-directory',
  getParentRoute: () => rootRouteImport,
} as any)
const OutcomesRoute = OutcomesRouteImport.update({
  id: '/outcomes',
  path: '/outcomes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchesRoute = LaunchesRouteImport.update({
  id: '/launches',
  path: '/launches',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const GetStartedRoute = GetStartedRouteImport.update({
  id: '/get-started',
  path: '/get-started',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerationRoute = GenerationRouteImport.update({
  id: '/generation',
  path: '/generation',
  getParentRoute: () => rootRouteImport,
} as any)
const FixItRoute = FixItRouteImport.update({
  id: '/fix-it',
  path: '/fix-it',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientProgressRoute = ClientProgressRouteImport.update({
  id: '/client-progress',
  path: '/client-progress',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesRoute = CasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportingIndexRoute = ReportingIndexRouteImport.update({
  id: '/reporting/',
  path: '/reporting/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersIndexRoute = ProvidersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProvidersRoute,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchesIndexRoute = LaunchesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LaunchesRoute,
} as any)
const CasesIndexRoute = CasesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CasesRoute,
} as any)
const TasksIdRoute = TasksIdRouteImport.update({
  id: '/tasks/$id',
  path: '/tasks/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportingPortfolioRoute = ReportingPortfolioRouteImport.update({
  id: '/reporting/portfolio',
  path: '/reporting/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersNewRoute = ProvidersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ProvidersRoute,
} as any)
const ProvidersIdRoute = ProvidersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProvidersRoute,
} as any)
const OnboardingWizardRoute = OnboardingWizardRouteImport.update({
  id: '/onboarding/wizard',
  path: '/onboarding/wizard',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchesIdRoute = LaunchesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LaunchesRoute,
} as any)
const GenerationRunsRoute = GenerationRunsRouteImport.update({
  id: '/generation_/runs',
  path: '/generation/runs',
  getParentRoute: () => rootRouteImport,
} as any)
const DevPrimitivesRoute = DevPrimitivesRouteImport.update({
  id: '/dev/primitives',
  path: '/dev/primitives',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesIdRoute = CasesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CasesRoute,
} as any)
const CaptureTokenRoute = CaptureTokenRouteImport.update({
  id: '/capture/$token',
  path: '/capture/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTemplatesRoute = AdminTemplatesRouteImport.update({
  id: '/admin/templates',
  path: '/admin/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStatusesRoute = AdminStatusesRouteImport.update({
  id: '/admin/statuses',
  path: '/admin/statuses',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSopsRoute = AdminSopsRouteImport.update({
  id: '/admin/sops',
  path: '/admin/sops',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPortalsRoute = AdminPortalsRouteImport.update({
  id: '/admin/portals',
  path: '/admin/portals',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPayersRoute = AdminPayersRouteImport.update({
  id: '/admin/payers',
  path: '/admin/payers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMsoRoutingRoute = AdminMsoRoutingRouteImport.update({
  id: '/admin/mso-routing',
  path: '/admin/mso-routing',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminImportRoute = AdminImportRouteImport.update({
  id: '/admin/import',
  path: '/admin/import',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersIdIndexRoute = ProvidersIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProvidersIdRoute,
} as any)
const GenerationRunsIndexRoute = GenerationRunsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GenerationRunsRoute,
} as any)
const AdminTemplatesIndexRoute = AdminTemplatesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminTemplatesRoute,
} as any)
const AdminSopsIndexRoute = AdminSopsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminSopsRoute,
} as any)
const ProvidersIdEditRoute = ProvidersIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ProvidersIdRoute,
} as any)
const PortalsPortalKeyTrainRoute = PortalsPortalKeyTrainRouteImport.update({
  id: '/portals/$portalKey/train',
  path: '/portals/$portalKey/train',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerationRunsRunIdRoute = GenerationRunsRunIdRouteImport.update({
  id: '/$runId',
  path: '/$runId',
  getParentRoute: () => GenerationRunsRoute,
} as any)
const AdminTemplatesNewRoute = AdminTemplatesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminTemplatesRoute,
} as any)
const AdminTemplatesIdRoute = AdminTemplatesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminTemplatesRoute,
} as any)
const AdminSopsIdRoute = AdminSopsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminSopsRoute,
} as any)
const AdminPayersIdScorecardRoute = AdminPayersIdScorecardRouteImport.update({
  id: '/admin/payers_/$id/scorecard',
  path: '/admin/payers/$id/scorecard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cases': typeof CasesRouteWithChildren
  '/client-progress': typeof ClientProgressRoute
  '/contact': typeof ContactRoute
  '/fix-it': typeof FixItRoute
  '/generation': typeof GenerationRoute
  '/get-started': typeof GetStartedRoute
  '/home': typeof HomeRoute
  '/launches': typeof LaunchesRouteWithChildren
  '/login': typeof LoginRoute
  '/outcomes': typeof OutcomesRoute
  '/payer-directory': typeof PayerDirectoryRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/progress': typeof ProgressRoute
  '/providers': typeof ProvidersRouteWithChildren
  '/reports': typeof ReportsRoute
  '/scope': typeof ScopeRoute
  '/soon': typeof SoonRoute
  '/welcome': typeof WelcomeRoute
  '/work': typeof WorkRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/import': typeof AdminImportRoute
  '/admin/mso-routing': typeof AdminMsoRoutingRoute
  '/admin/payers': typeof AdminPayersRoute
  '/admin/portals': typeof AdminPortalsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sops': typeof AdminSopsRouteWithChildren
  '/admin/statuses': typeof AdminStatusesRoute
  '/admin/templates': typeof AdminTemplatesRouteWithChildren
  '/capture/$token': typeof CaptureTokenRoute
  '/cases/$id': typeof CasesIdRoute
  '/dev/primitives': typeof DevPrimitivesRoute
  '/generation/runs': typeof GenerationRunsRouteWithChildren
  '/launches/$id': typeof LaunchesIdRoute
  '/onboarding/wizard': typeof OnboardingWizardRoute
  '/providers/$id': typeof ProvidersIdRouteWithChildren
  '/providers/new': typeof ProvidersNewRoute
  '/reporting/portfolio': typeof ReportingPortfolioRoute
  '/share/$token': typeof ShareTokenRoute
  '/tasks/$id': typeof TasksIdRoute
  '/cases/': typeof CasesIndexRoute
  '/launches/': typeof LaunchesIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/providers/': typeof ProvidersIndexRoute
  '/reporting/': typeof ReportingIndexRoute
  '/admin/sops/$id': typeof AdminSopsIdRoute
  '/admin/templates/$id': typeof AdminTemplatesIdRoute
  '/admin/templates/new': typeof AdminTemplatesNewRoute
  '/generation/runs/$runId': typeof GenerationRunsRunIdRoute
  '/portals/$portalKey/train': typeof PortalsPortalKeyTrainRoute
  '/providers/$id/edit': typeof ProvidersIdEditRoute
  '/admin/sops/': typeof AdminSopsIndexRoute
  '/admin/templates/': typeof AdminTemplatesIndexRoute
  '/generation/runs/': typeof GenerationRunsIndexRoute
  '/providers/$id/': typeof ProvidersIdIndexRoute
  '/admin/payers/$id/scorecard': typeof AdminPayersIdScorecardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/client-progress': typeof ClientProgressRoute
  '/contact': typeof ContactRoute
  '/fix-it': typeof FixItRoute
  '/generation': typeof GenerationRoute
  '/get-started': typeof GetStartedRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/outcomes': typeof OutcomesRoute
  '/payer-directory': typeof PayerDirectoryRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/progress': typeof ProgressRoute
  '/reports': typeof ReportsRoute
  '/scope': typeof ScopeRoute
  '/soon': typeof SoonRoute
  '/welcome': typeof WelcomeRoute
  '/work': typeof WorkRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/import': typeof AdminImportRoute
  '/admin/mso-routing': typeof AdminMsoRoutingRoute
  '/admin/payers': typeof AdminPayersRoute
  '/admin/portals': typeof AdminPortalsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/statuses': typeof AdminStatusesRoute
  '/capture/$token': typeof CaptureTokenRoute
  '/cases/$id': typeof CasesIdRoute
  '/dev/primitives': typeof DevPrimitivesRoute
  '/launches/$id': typeof LaunchesIdRoute
  '/onboarding/wizard': typeof OnboardingWizardRoute
  '/providers/new': typeof ProvidersNewRoute
  '/reporting/portfolio': typeof ReportingPortfolioRoute
  '/share/$token': typeof ShareTokenRoute
  '/tasks/$id': typeof TasksIdRoute
  '/cases': typeof CasesIndexRoute
  '/launches': typeof LaunchesIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/providers': typeof ProvidersIndexRoute
  '/reporting': typeof ReportingIndexRoute
  '/admin/sops/$id': typeof AdminSopsIdRoute
  '/admin/templates/$id': typeof AdminTemplatesIdRoute
  '/admin/templates/new': typeof AdminTemplatesNewRoute
  '/generation/runs/$runId': typeof GenerationRunsRunIdRoute
  '/portals/$portalKey/train': typeof PortalsPortalKeyTrainRoute
  '/providers/$id/edit': typeof ProvidersIdEditRoute
  '/admin/sops': typeof AdminSopsIndexRoute
  '/admin/templates': typeof AdminTemplatesIndexRoute
  '/generation/runs': typeof GenerationRunsIndexRoute
  '/providers/$id': typeof ProvidersIdIndexRoute
  '/admin/payers/$id/scorecard': typeof AdminPayersIdScorecardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cases': typeof CasesRouteWithChildren
  '/client-progress': typeof ClientProgressRoute
  '/contact': typeof ContactRoute
  '/fix-it': typeof FixItRoute
  '/generation': typeof GenerationRoute
  '/get-started': typeof GetStartedRoute
  '/home': typeof HomeRoute
  '/launches': typeof LaunchesRouteWithChildren
  '/login': typeof LoginRoute
  '/outcomes': typeof OutcomesRoute
  '/payer-directory': typeof PayerDirectoryRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/progress': typeof ProgressRoute
  '/providers': typeof ProvidersRouteWithChildren
  '/reports': typeof ReportsRoute
  '/scope': typeof ScopeRoute
  '/soon': typeof SoonRoute
  '/welcome': typeof WelcomeRoute
  '/work': typeof WorkRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/import': typeof AdminImportRoute
  '/admin/mso-routing': typeof AdminMsoRoutingRoute
  '/admin/payers': typeof AdminPayersRoute
  '/admin/portals': typeof AdminPortalsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sops': typeof AdminSopsRouteWithChildren
  '/admin/statuses': typeof AdminStatusesRoute
  '/admin/templates': typeof AdminTemplatesRouteWithChildren
  '/capture/$token': typeof CaptureTokenRoute
  '/cases/$id': typeof CasesIdRoute
  '/dev/primitives': typeof DevPrimitivesRoute
  '/generation_/runs': typeof GenerationRunsRouteWithChildren
  '/launches/$id': typeof LaunchesIdRoute
  '/onboarding/wizard': typeof OnboardingWizardRoute
  '/providers/$id': typeof ProvidersIdRouteWithChildren
  '/providers/new': typeof ProvidersNewRoute
  '/reporting/portfolio': typeof ReportingPortfolioRoute
  '/share/$token': typeof ShareTokenRoute
  '/tasks/$id': typeof TasksIdRoute
  '/cases/': typeof CasesIndexRoute
  '/launches/': typeof LaunchesIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/providers/': typeof ProvidersIndexRoute
  '/reporting/': typeof ReportingIndexRoute
  '/admin/sops/$id': typeof AdminSopsIdRoute
  '/admin/templates/$id': typeof AdminTemplatesIdRoute
  '/admin/templates/new': typeof AdminTemplatesNewRoute
  '/generation_/runs/$runId': typeof GenerationRunsRunIdRoute
  '/portals/$portalKey/train': typeof PortalsPortalKeyTrainRoute
  '/providers/$id/edit': typeof ProvidersIdEditRoute
  '/admin/sops/': typeof AdminSopsIndexRoute
  '/admin/templates/': typeof AdminTemplatesIndexRoute
  '/generation_/runs/': typeof GenerationRunsIndexRoute
  '/providers/$id/': typeof ProvidersIdIndexRoute
  '/admin/payers_/$id/scorecard': typeof AdminPayersIdScorecardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cases'
    | '/client-progress'
    | '/contact'
    | '/fix-it'
    | '/generation'
    | '/get-started'
    | '/home'
    | '/launches'
    | '/login'
    | '/outcomes'
    | '/payer-directory'
    | '/portfolio'
    | '/privacy'
    | '/progress'
    | '/providers'
    | '/reports'
    | '/scope'
    | '/soon'
    | '/welcome'
    | '/work'
    | '/admin/audit'
    | '/admin/import'
    | '/admin/mso-routing'
    | '/admin/payers'
    | '/admin/portals'
    | '/admin/settings'
    | '/admin/sops'
    | '/admin/statuses'
    | '/admin/templates'
    | '/capture/$token'
    | '/cases/$id'
    | '/dev/primitives'
    | '/generation/runs'
    | '/launches/$id'
    | '/onboarding/wizard'
    | '/providers/$id'
    | '/providers/new'
    | '/reporting/portfolio'
    | '/share/$token'
    | '/tasks/$id'
    | '/cases/'
    | '/launches/'
    | '/onboarding/'
    | '/providers/'
    | '/reporting/'
    | '/admin/sops/$id'
    | '/admin/templates/$id'
    | '/admin/templates/new'
    | '/generation/runs/$runId'
    | '/portals/$portalKey/train'
    | '/providers/$id/edit'
    | '/admin/sops/'
    | '/admin/templates/'
    | '/generation/runs/'
    | '/providers/$id/'
    | '/admin/payers/$id/scorecard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/client-progress'
    | '/contact'
    | '/fix-it'
    | '/generation'
    | '/get-started'
    | '/home'
    | '/login'
    | '/outcomes'
    | '/payer-directory'
    | '/portfolio'
    | '/privacy'
    | '/progress'
    | '/reports'
    | '/scope'
    | '/soon'
    | '/welcome'
    | '/work'
    | '/admin/audit'
    | '/admin/import'
    | '/admin/mso-routing'
    | '/admin/payers'
    | '/admin/portals'
    | '/admin/settings'
    | '/admin/statuses'
    | '/capture/$token'
    | '/cases/$id'
    | '/dev/primitives'
    | '/launches/$id'
    | '/onboarding/wizard'
    | '/providers/new'
    | '/reporting/portfolio'
    | '/share/$token'
    | '/tasks/$id'
    | '/cases'
    | '/launches'
    | '/onboarding'
    | '/providers'
    | '/reporting'
    | '/admin/sops/$id'
    | '/admin/templates/$id'
    | '/admin/templates/new'
    | '/generation/runs/$runId'
    | '/portals/$portalKey/train'
    | '/providers/$id/edit'
    | '/admin/sops'
    | '/admin/templates'
    | '/generation/runs'
    | '/providers/$id'
    | '/admin/payers/$id/scorecard'
  id:
    | '__root__'
    | '/'
    | '/cases'
    | '/client-progress'
    | '/contact'
    | '/fix-it'
    | '/generation'
    | '/get-started'
    | '/home'
    | '/launches'
    | '/login'
    | '/outcomes'
    | '/payer-directory'
    | '/portfolio'
    | '/privacy'
    | '/progress'
    | '/providers'
    | '/reports'
    | '/scope'
    | '/soon'
    | '/welcome'
    | '/work'
    | '/admin/audit'
    | '/admin/import'
    | '/admin/mso-routing'
    | '/admin/payers'
    | '/admin/portals'
    | '/admin/settings'
    | '/admin/sops'
    | '/admin/statuses'
    | '/admin/templates'
    | '/capture/$token'
    | '/cases/$id'
    | '/dev/primitives'
    | '/generation_/runs'
    | '/launches/$id'
    | '/onboarding/wizard'
    | '/providers/$id'
    | '/providers/new'
    | '/reporting/portfolio'
    | '/share/$token'
    | '/tasks/$id'
    | '/cases/'
    | '/launches/'
    | '/onboarding/'
    | '/providers/'
    | '/reporting/'
    | '/admin/sops/$id'
    | '/admin/templates/$id'
    | '/admin/templates/new'
    | '/generation_/runs/$runId'
    | '/portals/$portalKey/train'
    | '/providers/$id/edit'
    | '/admin/sops/'
    | '/admin/templates/'
    | '/generation_/runs/'
    | '/providers/$id/'
    | '/admin/payers_/$id/scorecard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CasesRoute: typeof CasesRouteWithChildren
  ClientProgressRoute: typeof ClientProgressRoute
  ContactRoute: typeof ContactRoute
  FixItRoute: typeof FixItRoute
  GenerationRoute: typeof GenerationRoute
  GetStartedRoute: typeof GetStartedRoute
  HomeRoute: typeof HomeRoute
  LaunchesRoute: typeof LaunchesRouteWithChildren
  LoginRoute: typeof LoginRoute
  OutcomesRoute: typeof OutcomesRoute
  PayerDirectoryRoute: typeof PayerDirectoryRoute
  PortfolioRoute: typeof PortfolioRoute
  PrivacyRoute: typeof PrivacyRoute
  ProgressRoute: typeof ProgressRoute
  ProvidersRoute: typeof ProvidersRouteWithChildren
  ReportsRoute: typeof ReportsRoute
  ScopeRoute: typeof ScopeRoute
  SoonRoute: typeof SoonRoute
  WelcomeRoute: typeof WelcomeRoute
  WorkRoute: typeof WorkRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminImportRoute: typeof AdminImportRoute
  AdminMsoRoutingRoute: typeof AdminMsoRoutingRoute
  AdminPayersRoute: typeof AdminPayersRoute
  AdminPortalsRoute: typeof AdminPortalsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSopsRoute: typeof AdminSopsRouteWithChildren
  AdminStatusesRoute: typeof AdminStatusesRoute
  AdminTemplatesRoute: typeof AdminTemplatesRouteWithChildren
  CaptureTokenRoute: typeof CaptureTokenRoute
  DevPrimitivesRoute: typeof DevPrimitivesRoute
  GenerationRunsRoute: typeof GenerationRunsRouteWithChildren
  OnboardingWizardRoute: typeof OnboardingWizardRoute
  ReportingPortfolioRoute: typeof ReportingPortfolioRoute
  ShareTokenRoute: typeof ShareTokenRoute
  TasksIdRoute: typeof TasksIdRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
  ReportingIndexRoute: typeof ReportingIndexRoute
  PortalsPortalKeyTrainRoute: typeof PortalsPortalKeyTrainRoute
  AdminPayersIdScorecardRoute: typeof AdminPayersIdScorecardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soon': {
      id: '/soon'
      path: '/soon'
      fullPath: '/soon'
      preLoaderRoute: typeof SoonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scope': {
      id: '/scope'
      path: '/scope'
      fullPath: '/scope'
      preLoaderRoute: typeof ScopeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers': {
      id: '/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof ProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payer-directory': {
      id: '/payer-directory'
      path: '/payer-directory'
      fullPath: '/payer-directory'
      preLoaderRoute: typeof PayerDirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outcomes': {
      id: '/outcomes'
      path: '/outcomes'
      fullPath: '/outcomes'
      preLoaderRoute: typeof OutcomesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launches': {
      id: '/launches'
      path: '/launches'
      fullPath: '/launches'
      preLoaderRoute: typeof LaunchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-started': {
      id: '/get-started'
      path: '/get-started'
      fullPath: '/get-started'
      preLoaderRoute: typeof GetStartedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generation': {
      id: '/generation'
      path: '/generation'
      fullPath: '/generation'
      preLoaderRoute: typeof GenerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fix-it': {
      id: '/fix-it'
      path: '/fix-it'
      fullPath: '/fix-it'
      preLoaderRoute: typeof FixItRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client-progress': {
      id: '/client-progress'
      path: '/client-progress'
      fullPath: '/client-progress'
      preLoaderRoute: typeof ClientProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reporting/': {
      id: '/reporting/'
      path: '/reporting'
      fullPath: '/reporting/'
      preLoaderRoute: typeof ReportingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers/': {
      id: '/providers/'
      path: '/'
      fullPath: '/providers/'
      preLoaderRoute: typeof ProvidersIndexRouteImport
      parentRoute: typeof ProvidersRoute
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launches/': {
      id: '/launches/'
      path: '/'
      fullPath: '/launches/'
      preLoaderRoute: typeof LaunchesIndexRouteImport
      parentRoute: typeof LaunchesRoute
    }
    '/cases/': {
      id: '/cases/'
      path: '/'
      fullPath: '/cases/'
      preLoaderRoute: typeof CasesIndexRouteImport
      parentRoute: typeof CasesRoute
    }
    '/tasks/$id': {
      id: '/tasks/$id'
      path: '/tasks/$id'
      fullPath: '/tasks/$id'
      preLoaderRoute: typeof TasksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reporting/portfolio': {
      id: '/reporting/portfolio'
      path: '/reporting/portfolio'
      fullPath: '/reporting/portfolio'
      preLoaderRoute: typeof ReportingPortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers/new': {
      id: '/providers/new'
      path: '/new'
      fullPath: '/providers/new'
      preLoaderRoute: typeof ProvidersNewRouteImport
      parentRoute: typeof ProvidersRoute
    }
    '/providers/$id': {
      id: '/providers/$id'
      path: '/$id'
      fullPath: '/providers/$id'
      preLoaderRoute: typeof ProvidersIdRouteImport
      parentRoute: typeof ProvidersRoute
    }
    '/onboarding/wizard': {
      id: '/onboarding/wizard'
      path: '/onboarding/wizard'
      fullPath: '/onboarding/wizard'
      preLoaderRoute: typeof OnboardingWizardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launches/$id': {
      id: '/launches/$id'
      path: '/$id'
      fullPath: '/launches/$id'
      preLoaderRoute: typeof LaunchesIdRouteImport
      parentRoute: typeof LaunchesRoute
    }
    '/generation_/runs': {
      id: '/generation_/runs'
      path: '/generation/runs'
      fullPath: '/generation/runs'
      preLoaderRoute: typeof GenerationRunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/primitives': {
      id: '/dev/primitives'
      path: '/dev/primitives'
      fullPath: '/dev/primitives'
      preLoaderRoute: typeof DevPrimitivesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/$id': {
      id: '/cases/$id'
      path: '/$id'
      fullPath: '/cases/$id'
      preLoaderRoute: typeof CasesIdRouteImport
      parentRoute: typeof CasesRoute
    }
    '/capture/$token': {
      id: '/capture/$token'
      path: '/capture/$token'
      fullPath: '/capture/$token'
      preLoaderRoute: typeof CaptureTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/templates': {
      id: '/admin/templates'
      path: '/admin/templates'
      fullPath: '/admin/templates'
      preLoaderRoute: typeof AdminTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/statuses': {
      id: '/admin/statuses'
      path: '/admin/statuses'
      fullPath: '/admin/statuses'
      preLoaderRoute: typeof AdminStatusesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sops': {
      id: '/admin/sops'
      path: '/admin/sops'
      fullPath: '/admin/sops'
      preLoaderRoute: typeof AdminSopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/portals': {
      id: '/admin/portals'
      path: '/admin/portals'
      fullPath: '/admin/portals'
      preLoaderRoute: typeof AdminPortalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payers': {
      id: '/admin/payers'
      path: '/admin/payers'
      fullPath: '/admin/payers'
      preLoaderRoute: typeof AdminPayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/mso-routing': {
      id: '/admin/mso-routing'
      path: '/admin/mso-routing'
      fullPath: '/admin/mso-routing'
      preLoaderRoute: typeof AdminMsoRoutingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/import': {
      id: '/admin/import'
      path: '/admin/import'
      fullPath: '/admin/import'
      preLoaderRoute: typeof AdminImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers/$id/': {
      id: '/providers/$id/'
      path: '/'
      fullPath: '/providers/$id/'
      preLoaderRoute: typeof ProvidersIdIndexRouteImport
      parentRoute: typeof ProvidersIdRoute
    }
    '/generation_/runs/': {
      id: '/generation_/runs/'
      path: '/'
      fullPath: '/generation/runs/'
      preLoaderRoute: typeof GenerationRunsIndexRouteImport
      parentRoute: typeof GenerationRunsRoute
    }
    '/admin/templates/': {
      id: '/admin/templates/'
      path: '/'
      fullPath: '/admin/templates/'
      preLoaderRoute: typeof AdminTemplatesIndexRouteImport
      parentRoute: typeof AdminTemplatesRoute
    }
    '/admin/sops/': {
      id: '/admin/sops/'
      path: '/'
      fullPath: '/admin/sops/'
      preLoaderRoute: typeof AdminSopsIndexRouteImport
      parentRoute: typeof AdminSopsRoute
    }
    '/providers/$id/edit': {
      id: '/providers/$id/edit'
      path: '/edit'
      fullPath: '/providers/$id/edit'
      preLoaderRoute: typeof ProvidersIdEditRouteImport
      parentRoute: typeof ProvidersIdRoute
    }
    '/portals/$portalKey/train': {
      id: '/portals/$portalKey/train'
      path: '/portals/$portalKey/train'
      fullPath: '/portals/$portalKey/train'
      preLoaderRoute: typeof PortalsPortalKeyTrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generation_/runs/$runId': {
      id: '/generation_/runs/$runId'
      path: '/$runId'
      fullPath: '/generation/runs/$runId'
      preLoaderRoute: typeof GenerationRunsRunIdRouteImport
      parentRoute: typeof GenerationRunsRoute
    }
    '/admin/templates/new': {
      id: '/admin/templates/new'
      path: '/new'
      fullPath: '/admin/templates/new'
      preLoaderRoute: typeof AdminTemplatesNewRouteImport
      parentRoute: typeof AdminTemplatesRoute
    }
    '/admin/templates/$id': {
      id: '/admin/templates/$id'
      path: '/$id'
      fullPath: '/admin/templates/$id'
      preLoaderRoute: typeof AdminTemplatesIdRouteImport
      parentRoute: typeof AdminTemplatesRoute
    }
    '/admin/sops/$id': {
      id: '/admin/sops/$id'
      path: '/$id'
      fullPath: '/admin/sops/$id'
      preLoaderRoute: typeof AdminSopsIdRouteImport
      parentRoute: typeof AdminSopsRoute
    }
    '/admin/payers_/$id/scorecard': {
      id: '/admin/payers_/$id/scorecard'
      path: '/admin/payers/$id/scorecard'
      fullPath: '/admin/payers/$id/scorecard'
      preLoaderRoute: typeof AdminPayersIdScorecardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CasesRouteChildren {
  CasesIdRoute: typeof CasesIdRoute
  CasesIndexRoute: typeof CasesIndexRoute
}

const CasesRouteChildren: CasesRouteChildren = {
  CasesIdRoute: CasesIdRoute,
  CasesIndexRoute: CasesIndexRoute,
}

const CasesRouteWithChildren = CasesRoute._addFileChildren(CasesRouteChildren)

interface LaunchesRouteChildren {
  LaunchesIdRoute: typeof LaunchesIdRoute
  LaunchesIndexRoute: typeof LaunchesIndexRoute
}

const LaunchesRouteChildren: LaunchesRouteChildren = {
  LaunchesIdRoute: LaunchesIdRoute,
  LaunchesIndexRoute: LaunchesIndexRoute,
}

const LaunchesRouteWithChildren = LaunchesRoute._addFileChildren(
  LaunchesRouteChildren,
)

interface ProvidersIdRouteChildren {
  ProvidersIdEditRoute: typeof ProvidersIdEditRoute
  ProvidersIdIndexRoute: typeof ProvidersIdIndexRoute
}

const ProvidersIdRouteChildren: ProvidersIdRouteChildren = {
  ProvidersIdEditRoute: ProvidersIdEditRoute,
  ProvidersIdIndexRoute: ProvidersIdIndexRoute,
}

const ProvidersIdRouteWithChildren = ProvidersIdRoute._addFileChildren(
  ProvidersIdRouteChildren,
)

interface ProvidersRouteChildren {
  ProvidersIdRoute: typeof ProvidersIdRouteWithChildren
  ProvidersNewRoute: typeof ProvidersNewRoute
  ProvidersIndexRoute: typeof ProvidersIndexRoute
}

const ProvidersRouteChildren: ProvidersRouteChildren = {
  ProvidersIdRoute: ProvidersIdRouteWithChildren,
  ProvidersNewRoute: ProvidersNewRoute,
  ProvidersIndexRoute: ProvidersIndexRoute,
}

const ProvidersRouteWithChildren = ProvidersRoute._addFileChildren(
  ProvidersRouteChildren,
)

interface AdminSopsRouteChildren {
  AdminSopsIdRoute: typeof AdminSopsIdRoute
  AdminSopsIndexRoute: typeof AdminSopsIndexRoute
}

const AdminSopsRouteChildren: AdminSopsRouteChildren = {
  AdminSopsIdRoute: AdminSopsIdRoute,
  AdminSopsIndexRoute: AdminSopsIndexRoute,
}

const AdminSopsRouteWithChildren = AdminSopsRoute._addFileChildren(
  AdminSopsRouteChildren,
)

interface AdminTemplatesRouteChildren {
  AdminTemplatesIdRoute: typeof AdminTemplatesIdRoute
  AdminTemplatesNewRoute: typeof AdminTemplatesNewRoute
  AdminTemplatesIndexRoute: typeof AdminTemplatesIndexRoute
}

const AdminTemplatesRouteChildren: AdminTemplatesRouteChildren = {
  AdminTemplatesIdRoute: AdminTemplatesIdRoute,
  AdminTemplatesNewRoute: AdminTemplatesNewRoute,
  AdminTemplatesIndexRoute: AdminTemplatesIndexRoute,
}

const AdminTemplatesRouteWithChildren = AdminTemplatesRoute._addFileChildren(
  AdminTemplatesRouteChildren,
)

interface GenerationRunsRouteChildren {
  GenerationRunsRunIdRoute: typeof GenerationRunsRunIdRoute
  GenerationRunsIndexRoute: typeof GenerationRunsIndexRoute
}

const GenerationRunsRouteChildren: GenerationRunsRouteChildren = {
  GenerationRunsRunIdRoute: GenerationRunsRunIdRoute,
  GenerationRunsIndexRoute: GenerationRunsIndexRoute,
}

const GenerationRunsRouteWithChildren = GenerationRunsRoute._addFileChildren(
  GenerationRunsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CasesRoute: CasesRouteWithChildren,
  ClientProgressRoute: ClientProgressRoute,
  ContactRoute: ContactRoute,
  FixItRoute: FixItRoute,
  GenerationRoute: GenerationRoute,
  GetStartedRoute: GetStartedRoute,
  HomeRoute: HomeRoute,
  LaunchesRoute: LaunchesRouteWithChildren,
  LoginRoute: LoginRoute,
  OutcomesRoute: OutcomesRoute,
  PayerDirectoryRoute: PayerDirectoryRoute,
  PortfolioRoute: PortfolioRoute,
  PrivacyRoute: PrivacyRoute,
  ProgressRoute: ProgressRoute,
  ProvidersRoute: ProvidersRouteWithChildren,
  ReportsRoute: ReportsRoute,
  ScopeRoute: ScopeRoute,
  SoonRoute: SoonRoute,
  WelcomeRoute: WelcomeRoute,
  WorkRoute: WorkRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminImportRoute: AdminImportRoute,
  AdminMsoRoutingRoute: AdminMsoRoutingRoute,
  AdminPayersRoute: AdminPayersRoute,
  AdminPortalsRoute: AdminPortalsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSopsRoute: AdminSopsRouteWithChildren,
  AdminStatusesRoute: AdminStatusesRoute,
  AdminTemplatesRoute: AdminTemplatesRouteWithChildren,
  CaptureTokenRoute: CaptureTokenRoute,
  DevPrimitivesRoute: DevPrimitivesRoute,
  GenerationRunsRoute: GenerationRunsRouteWithChildren,
  OnboardingWizardRoute: OnboardingWizardRoute,
  ReportingPortfolioRoute: ReportingPortfolioRoute,
  ShareTokenRoute: ShareTokenRoute,
  TasksIdRoute: TasksIdRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
  ReportingIndexRoute: ReportingIndexRoute,
  PortalsPortalKeyTrainRoute: PortalsPortalKeyTrainRoute,
  AdminPayersIdScorecardRoute: AdminPayersIdScorecardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
