-- E4.5 TE-2 — the private, repository-managed Storage bucket for provider &
-- group documents, with an organization-bound object path contract.
--
-- Path contract (object keys are generated by the SERVER service, never
-- accepted verbatim from the browser):
--   org/{orgId}/{provider|group}/{ownerId}/{familyId}/{version}/{safeFileName}
--
-- The bucket is NON-PUBLIC and no permanent public URL is ever stored or
-- returned: all object access is a short-lived signed URL minted by the
-- guarded /api layer (TE-3), or — defense in depth — a direct authenticated
-- storage call bounded by the storage.objects policies below, which validate
-- the path's org segment against the caller's membership. Writes are limited
-- to admin/specialist (mirroring the metadata insert policy); reads follow
-- the existing organization-member permission (billing reads too). There are
-- NO update/delete policies: objects are immutable — a replacement uploads a
-- NEW versioned path (TE-1).
--
-- The bucket-level size/MIME limits are the storage-side backstop of the
-- limits centralized in src/lib/documents.ts (TE-4): 25 MiB, PDF/PNG/JPEG.
--
-- Guarded on the storage schema so a bare-Postgres repo rebuild (no storage
-- extension) still passes; local Supabase stacks and hosted both have it.
-- Applying to hosted is an OPERATOR task — see the PR body.

-- Parse the org id out of an object key under the E4.5 path contract.
-- Returns NULL for any malformed key (wrong prefix, non-uuid segment), so
-- policies fail CLOSED without a cast error.
CREATE OR REPLACE FUNCTION public.document_storage_org_id(p_name text)
RETURNS uuid
LANGUAGE plpgsql
IMMUTABLE
SET search_path TO 'public'
AS $$
DECLARE
  v_parts text[];
BEGIN
  v_parts := string_to_array(coalesce(p_name, ''), '/');
  IF array_length(v_parts, 1) IS NULL OR array_length(v_parts, 1) < 2 THEN
    RETURN NULL;
  END IF;
  IF v_parts[1] <> 'org' THEN
    RETURN NULL;
  END IF;
  IF v_parts[2] !~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$' THEN
    RETURN NULL;
  END IF;
  RETURN v_parts[2]::uuid;
END;
$$;
REVOKE ALL ON FUNCTION public.document_storage_org_id(text) FROM public, anon;
GRANT EXECUTE ON FUNCTION public.document_storage_org_id(text) TO authenticated, service_role;

DO $$
BEGIN
  IF to_regclass('storage.buckets') IS NULL THEN
    RAISE NOTICE 'storage schema absent — skipping bucket + policies (repo-only rebuild)';
    RETURN;
  END IF;

  INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
  VALUES (
    'provider-documents',
    'provider-documents',
    false,
    26214400, -- 25 MiB, mirrored by DOCUMENT_MAX_BYTES in src/lib/documents.ts
    ARRAY['application/pdf', 'image/png', 'image/jpeg']
  )
  ON CONFLICT (id) DO UPDATE SET
    public = false,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

  -- Reads: any member of the org named in the object path. NULL org (malformed
  -- path) never matches — fail closed.
  DROP POLICY IF EXISTS provider_documents_objects_select ON storage.objects;
  CREATE POLICY provider_documents_objects_select ON storage.objects
    FOR SELECT TO authenticated
    USING (
      bucket_id = 'provider-documents'
      AND public.document_storage_org_id(name) IN (SELECT public.user_org_ids())
    );

  -- Writes: admin/specialist of that org only (mirrors the metadata policy).
  DROP POLICY IF EXISTS provider_documents_objects_insert ON storage.objects;
  CREATE POLICY provider_documents_objects_insert ON storage.objects
    FOR INSERT TO authenticated
    WITH CHECK (
      bucket_id = 'provider-documents'
      AND public.document_storage_org_id(name) IN (SELECT public.user_org_ids())
      AND public.user_role(public.document_storage_org_id(name)) = ANY (ARRAY['admin', 'specialist'])
    );

  -- Deliberately NO update/delete policies: objects are immutable from every
  -- client path. The server's bounded orphan sweep (TE-4) runs on the
  -- service-role client, which bypasses RLS by design.
END $$;
