-- Payer PDF (Story 1/2) — the GLOBAL catalog of blank, payer-specific PDF forms
-- attached to a SOP template, plus the private Storage bucket that holds them.
--
-- WHY A NEW TABLE AND BUCKET, not the provider_documents vault: that vault is
-- org-scoped and provider/group-owned (path `org/{orgId}/{provider|group}/…`,
-- DocumentOwnerType = provider|group). A payer's blank form is neither — it is
-- global truth about the payer, the same file for every org that credentials
-- with them, and it belongs to no provider. Squeezing it into the vault would
-- have meant a fake owner and one copy per org.
--
-- TIER: rows carry NO org_id. They are global, exactly like `sop_templates`
-- rows authored by the Template Editor (org_id NULL) and the shared
-- portal/field-map catalog. There is therefore nothing to widen them to —
-- which is what keeps a global read from leaking any org's private data.
--
-- FAMILY / VERSION (mirrors the vault's derived-current rule): `family_id` is
-- the stable identity a TEMPLATE ACTION points at; each upload under that
-- family is an immutable row at `version`. "Current" is derived — the highest
-- version in the family with retired_at IS NULL — never a flag. Replace =
-- INSERT a new version (supersedes_id → the prior row). Delete = soft retire
-- (`retired_at`), so a case generated earlier still resolves the exact file it
-- was generated with.
--
-- WRITES: there is deliberately NO client INSERT policy. Uploads run through
-- the guarded /api signing boundary on the service-role client
-- (POST /api/payer-forms/upload-intent → finalize), the same shape as
-- /api/documents/*, because a signed Storage URL cannot be minted in the
-- browser. Retire is metadata-only (no Storage involvement) and so stays on
-- RLS, gated by `user_is_admin_anywhere()`.
--
-- Path contract (generated by the SERVER, never accepted verbatim from the
-- browser):
--   payer/{payerId}/{familyId}/{version}/{safeFileName}

CREATE TABLE IF NOT EXISTS public.payer_forms (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  -- The template the form was uploaded on. A form follows its template, which
  -- is what makes payer + states read-only context rather than manual tagging.
  template_id uuid NOT NULL REFERENCES public.sop_templates(id) ON DELETE CASCADE,
  -- Denormalized from the template at upload time so the Storage path and the
  -- catalog read never need a join. The template's payer never changes.
  payer_id uuid NOT NULL REFERENCES public.payers(id),
  family_id uuid NOT NULL DEFAULT gen_random_uuid(),
  version integer NOT NULL DEFAULT 1,
  -- The trainer's descriptive name ("PT Credentialing Supplement"). Required,
  -- and deliberately NOT derived from the file name: payer downloads are named
  -- things like `form_2024_v3_FINAL.pdf`.
  label text NOT NULL,
  file_name text NOT NULL,
  storage_path text NOT NULL,
  mime_type text NOT NULL DEFAULT 'application/pdf',
  byte_size bigint NOT NULL,
  supersedes_id uuid REFERENCES public.payer_forms(id),
  retired_at timestamptz,
  retired_by uuid,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by uuid,
  CONSTRAINT payer_forms_family_version_key UNIQUE (family_id, version),
  CONSTRAINT payer_forms_storage_path_key UNIQUE (storage_path),
  CONSTRAINT payer_forms_label_not_blank CHECK (btrim(label) <> ''),
  CONSTRAINT payer_forms_file_name_not_blank CHECK (btrim(file_name) <> ''),
  CONSTRAINT payer_forms_version_positive CHECK (version >= 1),
  CONSTRAINT payer_forms_byte_size_positive CHECK (byte_size > 0),
  -- PDF only. The bucket-level allowed_mime_types below is the storage-side
  -- backstop of the same rule.
  CONSTRAINT payer_forms_mime_pdf CHECK (mime_type = 'application/pdf')
);

CREATE INDEX IF NOT EXISTS payer_forms_template_idx
  ON public.payer_forms (template_id)
  WHERE retired_at IS NULL;
CREATE INDEX IF NOT EXISTS payer_forms_family_idx
  ON public.payer_forms (family_id);
CREATE INDEX IF NOT EXISTS payer_forms_payer_idx
  ON public.payer_forms (payer_id);

-- Is the caller an admin of ANY org? Global rows belong to no org, so
-- `user_role(org)` has no org to be asked about. SECURITY DEFINER so the
-- membership read does not recurse through memberships' own RLS.
CREATE OR REPLACE FUNCTION public.user_is_admin_anywhere()
RETURNS boolean
LANGUAGE sql
STABLE SECURITY DEFINER
SET search_path TO 'public'
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.memberships m
    WHERE m.user_id = auth.uid() AND m.role = 'admin'
  );
$$;
REVOKE ALL ON FUNCTION public.user_is_admin_anywhere() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.user_is_admin_anywhere() TO authenticated, service_role;

ALTER TABLE public.payer_forms ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON public.payer_forms FROM PUBLIC;
REVOKE ALL ON public.payer_forms FROM anon;
GRANT SELECT, UPDATE ON public.payer_forms TO authenticated;
GRANT ALL ON public.payer_forms TO service_role;

-- Reads: any authenticated member. A blank payer form is global truth and
-- carries no tenant data — the same posture as the shared portal registry.
DROP POLICY IF EXISTS payer_forms_select ON public.payer_forms;
CREATE POLICY payer_forms_select ON public.payer_forms
  FOR SELECT TO authenticated
  USING (true);

-- Retire (soft delete) is the ONE client write: admins only, and it may only
-- ever set retired_at. Every other column is immutable from the client, which
-- is what keeps a "replace" an INSERT of a new version rather than an edit.
DROP POLICY IF EXISTS payer_forms_retire ON public.payer_forms;
CREATE POLICY payer_forms_retire ON public.payer_forms
  FOR UPDATE TO authenticated
  USING (public.user_is_admin_anywhere())
  WITH CHECK (public.user_is_admin_anywhere());

CREATE OR REPLACE FUNCTION public.payer_forms_retire_only()
RETURNS trigger
LANGUAGE plpgsql
SET search_path TO 'public'
AS $$
BEGIN
  -- service_role (the /api upload path) is exempt: it inserts, it never
  -- UPDATEs, so this only ever guards a client-issued update.
  IF NEW.id IS DISTINCT FROM OLD.id
     OR NEW.template_id IS DISTINCT FROM OLD.template_id
     OR NEW.payer_id IS DISTINCT FROM OLD.payer_id
     OR NEW.family_id IS DISTINCT FROM OLD.family_id
     OR NEW.version IS DISTINCT FROM OLD.version
     OR NEW.label IS DISTINCT FROM OLD.label
     OR NEW.file_name IS DISTINCT FROM OLD.file_name
     OR NEW.storage_path IS DISTINCT FROM OLD.storage_path
     OR NEW.mime_type IS DISTINCT FROM OLD.mime_type
     OR NEW.byte_size IS DISTINCT FROM OLD.byte_size
     OR NEW.supersedes_id IS DISTINCT FROM OLD.supersedes_id
     OR NEW.created_at IS DISTINCT FROM OLD.created_at
     OR NEW.created_by IS DISTINCT FROM OLD.created_by
  THEN
    RAISE EXCEPTION 'payer_forms rows are immutable; only retired_at/retired_by may change'
      USING ERRCODE = 'check_violation';
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS payer_forms_retire_only_trg ON public.payer_forms;
CREATE TRIGGER payer_forms_retire_only_trg
  BEFORE UPDATE ON public.payer_forms
  FOR EACH ROW EXECUTE FUNCTION public.payer_forms_retire_only();

-- ---------------------------------------------------------------------------
-- Storage: the private `payer-forms` bucket.
--
-- Guarded on the storage schema so a bare-Postgres repo rebuild (no storage
-- extension) still passes — the same shape as 20260717150100.
-- ---------------------------------------------------------------------------

DO $$
BEGIN
  IF to_regclass('storage.buckets') IS NULL THEN
    RAISE NOTICE 'storage schema absent — skipping bucket + policies (repo-only rebuild)';
    RETURN;
  END IF;

  INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
  VALUES (
    'payer-forms',
    'payer-forms',
    false,
    26214400, -- 25 MiB, mirrored by PAYER_FORM_MAX_BYTES in src/lib/payerForms.ts
    ARRAY['application/pdf']
  )
  ON CONFLICT (id) DO UPDATE SET
    public = false,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

  -- Reads: any authenticated member, matching the metadata policy. Defense in
  -- depth only — every browser read goes through the signed-URL route.
  DROP POLICY IF EXISTS payer_forms_objects_select ON storage.objects;
  CREATE POLICY payer_forms_objects_select ON storage.objects
    FOR SELECT TO authenticated
    USING (bucket_id = 'payer-forms');

  -- Deliberately NO insert/update/delete policies: objects are written only by
  -- the service-role client behind the /api signing boundary, and are
  -- immutable once written (a replace is a new versioned path).
END $$;
